name = "multiplex_limit"
uuid = "059162a1-7293-4ce2-8f6a-544ae95c106f"
authors = ["Charles Dufour"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
